# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: klakegg/hugo:0.100.2-ext-debian-ci
    working_directory: "/src"
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "prepare"
          command: "mkdir -p /dist"
      - run:
          name: "build"
          command: "hugo --destination dist"
      - run:
          name: "check"
          command: "ls dist"
      # - run:
      #     name: Compress Artifacts
      #     command: tar -cvzf /dist/dist.tar dist
      # - store_artifacts:
      #     path: /dist
      #     destination: dist
      - run:
          name: "apt update"
          command: apt update
      - run:
          name: "apt install curl"
          command: apt install curl -y
      - run:
          name: "install docker"
          command: curl -fsSL https://get.docker.com -o get-docker.sh && sh ./get-docker.sh
      - run:
          name: "set version"
          command: | 
            echo 'export timestamp=$(date +%Y%m%d%H%M%S)'
            source "$BASH_ENV"
      - run:
          name: "build image"
          command: "docker build --tag registry.danielras.com:5443/blog:$timestamp ."
      - deploy:
          name: "Push application Docker image"
          command: |
            docker push registry.danielras.com:5443/blog:$timestamp

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
